### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by paymog** [0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video#2]
Thank you for making this script - I've been looking for something like this for months now! 

Unfortunately, I'm having some trouble getting this to work. I'm using Brave Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64) on macos 11.6. I've added Tampermonkey and added this script:

![image](https://user-images.githubusercontent.com/1986950/134959786-5d890d01-f495-4469-baab-ae03665cb97b.png)

but when I hold `ctrl` and click on a video I get the context menu:

![image](https://user-images.githubusercontent.com/1986950/134959844-897af36a-a3f6-4c53-9f4a-c0ce28a9d9df.png)

when I hold `option` and click on the a video I get and download menu:

![image](https://user-images.githubusercontent.com/1986950/134959935-59d5b3d6-e7f1-4acb-81f9-1c190ea72429.png)

Do you have any idea why this might be happening?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
You need to hold down ctrl/alt key and move your mouse over the video. See this demo carefully:
https://raw.githubusercontent.com/0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video/main/youtube.gif

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Btw, it still works and I'm using it every day.

**Comment by paymog** [comment]
Ah got it! I didn't realize you have to hold control when the cursor is *not* over a video and then move the cursor over the video you want mark as not interested. Thanks for the support!
