### ISSUE TITLE
can this be installed with userscript.zone?

### ISSUE THREAD

**Issue by paymog** [0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video#3]
Can this script be installed with https://www.userscript.zone/? I've tried searching for it there but haven't been able to find it - maybe I'm searching the wrong keywords?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I haven't put it there before. But not it's at https://greasyfork.org/en/scripts/436380-i-m-not-interested-in-this-youtube-video
