### ISSUE TITLE
Doesn't work on Youtube 2022

### ISSUE THREAD

**Issue by oldmill1** [0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video#4]
Seems to not be working as of now. :( Tried on TM

**Comment by oldmill1** [comment]
<img width="666" alt="Screen Shot 2022-08-18 at 15 18 17" src="https://user-images.githubusercontent.com/384512/185476524-c740dc7d-2239-497c-9ec2-cd4ddfdcbdd4.png">

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I tried and it works here. You need to press `Ctrl` or `Alt` key, and then move your mouse cursor hover over the videos. Do you operate this way?

**Comment by heosphoros** [comment]
it works
Man can you do this for shorts, i want to block the channel of thouse annoying spammers videos, the button is hidden under the 3 dots ...
thanks man .. hope you can make it
and btw the script is verry helpfull tnx again

**Comment by nanimosiranai** [comment]
Thanks for updating this useful script.
