### ISSUE TITLE
Console Errors (Can't find any cells to check)

### ISSUE THREAD

**Issue by ylluminarious** [0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video#5]
Hovering over videos with `Ctrl` or `Alt` isn't removing videos anymore. I'm also seeing many repeated `Can't find any cells to check` messages in the console. I'm guessing that Youtube has updated their DOM identifiers and that the script needs to be updated...

**Comment by misspent** [comment]
Change `ytd-rich-item-renderer.style-scope.ytd-rich-grid-row` to `ytd-rich-item-renderer.ytd-rich-grid-renderer.style-scope`

**Comment by ylluminarious** [comment]
@misspent Thanks, can confirm that worked... I suppose I'll leave this issue open for now, though, until a fix is pushed to master, so that others can see this.

I'm not sure if the developer would accept a PR, but I'd be willing to make one if so.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I've updated the script based on @misspent's suggestion. Thanks guys for reporting and the suggestion.
