### ISSUE TITLE
dosen't work in nov 16th 2024

### ISSUE THREAD

**Issue by luluijn** [0x7FFFFFFFFFFFFFFF/I_am_not_interested_in_this_youtube_video#6]
Seems youtube updated again.
my chrome version 131.0.6778.70
tampermonkey v5.3.2

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Could you try the new version?

**Comment by luluijn** [comment]
ye,i tried 11/22/2024 version but still dosen't work

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> ye,i tried 11/22/2024 version but still dosen't work

Try again.

**Comment by luluijn** [comment]
Thank you for your reply, but the console shows the issue: 'This document requires 'TrustedHTML' assignment.'
![20241207145444](https://github.com/user-attachments/assets/281bc995-72ee-40d4-880c-39965aa965db)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Thank you for your reply, but the console shows the issue: 'This document requires 'TrustedHTML' assignment.' ![20241207145444](https://private-user-images.githubusercontent.com/10826949/393485186-281bc995-72ee-40d4-880c-39965aa965db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODE1MzQsIm5iZiI6MTczMzU4MTIzNCwicGF0aCI6Ii8xMDgyNjk0OS8zOTM0ODUxODYtMjgxYmM5OTUtNzJlZS00MGQ0LTg4MGMtMzk5NjVhYTk2NWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTY4ODVmNmRlMDNiOGU3YWI5NTJmMzk4Nzg0ZjJlZWU2YjdkOTQ4YzRhYmIyM2MwMWQwYmUwMTZhNjUyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UuVOBwubQtQw5uD_m_phju-bvNd_GQcFeWK675WVS3I)

I think I know why it failed. Please update to the newest version and see if it works.

**Comment by luluijn** [comment]
thank you very much.It's work. your scipt is amazing!
